template-file-path: infra/cfn/pipeline.template.yaml

parameters:
  ConnectionArn: arn:aws:codeconnections:us-east-1:874851036047:connection/220eff36-4ed2-4af1-bc11-537b084891b8
  RepoOwner: efi98
  RepoName: user-managment
  BranchName: main
  EcrRepoUri: 874851036047.dkr.ecr.us-east-1.amazonaws.com/valkey-backend
  EcsClusterName: user-managment-app
  EcsServiceName: user-managment-app
  FrontendBucketName: user-management-fronfend
  CloudFrontDistributionId: E1DPJ9CKSIXIA
  AwsRegion: us-east-1

tags:
  app: user-management
  managed-by: cloudformation-git-sync
